# Generated by Django 3.1.2 on 2020-10-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0008_auto_20191202_0809'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='due',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
